# Generated by Django 3.2 on 2021-04-21 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0003_blog_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='auther',
            new_name='writer',
        ),
    ]
