# Generated by Django 3.2 on 2021-04-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0004_rename_auther_blog_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d'),
        ),
    ]
