# Generated by Django 3.2 on 2021-04-22 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogg', '0005_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='like',
            field=models.ManyToManyField(related_name='BlogLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
