# Generated by Django 3.2 on 2021-04-23 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0010_auto_20210423_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='video',
        ),
    ]
