# Generated by Django 3.2 on 2021-04-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0011_remove_blog_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSliderShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SliderShow', models.ImageField(upload_to='slidershow')),
            ],
        ),
    ]
