# Generated by Django 3.2 on 2021-04-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0012_blogslidershow'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogslidershow',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
