# Generated by Django 3.2 on 2021-04-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0013_blogslidershow_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogSliderShow',
        ),
    ]
